package com.denik.web.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class LicenseReportController {

    // Forward requests without the filename to the static index.html generated by the license report
    @GetMapping({"/dependency-license", "/dependency-license/"})
    public String forwardToReportIndex() {
        return "forward:/dependency-license/index.html";
    }
}

